const REST=['https://data-api.binance.vision','https://api.binance.com'];
const WS=['wss://data-stream.binance.vision','wss://stream.binance.com:9443'];
const TFS=['1m','5m','15m','1h','4h','1d'];
const POPULAR=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','AVAXUSDT','DOTUSDT','LINKUSDT','LTCUSDT','ATOMUSDT','UNIUSDT','NEARUSDT','APTUSDT','ARBUSDT','OPUSDT','SUIUSDT','PEPEUSDT','WIFUSDT'];
let symbol='BTCUSDT',tf='15m',bars=[],chart,series,volS,ws;
let showS=true,showV=true,theme='dark',tradeMode=false,tool='cross',orders=[],_oid=1,position=null,dragOrd=null;
let autoBr=true,slPct=0.4,tpPct=0.8,ctxPrice=null;
let watch=JSON.parse(localStorage.getItem('tt_watch')||'["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT"]');
const _cfg=JSON.parse(localStorage.getItem('tt_cfg')||'{}');
if(_cfg.tf) tf=_cfg.tf;
if(typeof _cfg.showS==='boolean') showS=_cfg.showS;
if(typeof _cfg.showV==='boolean') showV=_cfg.showV;
if(_cfg.theme==='light'||_cfg.theme==='dark') theme=_cfg.theme;
if(typeof _cfg.autoBr==='boolean') autoBr=_cfg.autoBr;
if(_cfg.slPct) slPct=+_cfg.slPct;if(_cfg.tpPct) tpPct=+_cfg.tpPct;
function saveCfg(){localStorage.setItem('tt_cfg',JSON.stringify({tf,showS,showV,theme,autoBr,slPct,tpPct}))}
let tickers=[];
const $=id=>document.getElementById(id);
let _toastT=null;
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.add('on');clearTimeout(_toastT);_toastT=setTimeout(()=>el.classList.remove('on'),1800)}
function setConn(s){const c=$('connDot');if(c){c.className='conn '+s}}
const st=t=>{const el=$('stTxt');if(el)el.textContent=t};
const fmt=v=>v==null?'—':v>=1000?v.toFixed(1):v>=1?v.toFixed(2):v.toFixed(5);
const saveWatch=()=>localStorage.setItem('tt_watch',JSON.stringify(watch));
const qty=()=>{const q=parseFloat($('trQty').value);return(isFinite(q)&&q>0)?q:0.01};
const lastPx=()=>bars.length?bars[bars.length-1].close:null;
document.querySelectorAll('.nav button').forEach(b=>{b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('pg-'+b.dataset.p).classList.add('on');if(b.dataset.p==='chart'){const fix=()=>{const el=$('chart');if(!el||!chart)return;const w=el.clientWidth,h=el.clientHeight;if(w&&h){chart.applyOptions({width:w,height:h});resize();draw()}};requestAnimationFrame(()=>{fix();setTimeout(fix,50);setTimeout(fix,200)})}if(b.dataset.p==='screen')loadTickers();if(b.dataset.p==='watch')renderWatch();if(b.dataset.p==='trade')renderTrade()}});
async function load(){st('загрузка…');setConn('wait');for(let attempt=0;attempt<3;attempt++){for(const b of REST){try{const r=await fetch(b+'/api/v3/klines?symbol='+symbol+'&interval='+tf+'&limit=250',{cache:'no-store'});if(!r.ok)continue;const raw=await r.json();if(!Array.isArray(raw))continue;bars=raw.map(k=>({time:k[0]/1000|0,open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]}));setConn('ok');return true}catch(e){}}if(attempt<2)await new Promise(r=>setTimeout(r,600*(attempt+1)))}st('ошибка сети');setConn('bad');toast('Нет связи с биржей');return false}
function wsConn(){if(ws)try{ws.close()}catch(e){}const s=symbol.toLowerCase()+'@kline_'+tf;let i=0;(function c(){if(i>=WS.length)return;try{ws=new WebSocket(WS[i++]+'/ws/'+s);ws.onopen=()=>setConn('ok');ws.onmessage=e=>{try{const k=JSON.parse(e.data).k;const bar={time:k.t/1000|0,open:+k.o,high:+k.h,low:+k.l,close:+k.c,volume:+k.v};if(series)series.update(bar);if(volS)volS.update({time:bar.time,value:bar.volume,color:theme==='light'?(bar.close>=bar.open?'rgba(0,0,0,.22)':'rgba(0,0,0,.1)'):(bar.close>=bar.open?'rgba(48,209,88,.3)':'rgba(255,69,58,.3)')});const L=bars[bars.length-1];if(L&&L.time===bar.time)bars[bars.length-1]=bar;else bars.push(bar);if(bars.length>300)bars.shift();$('last').textContent=fmt(bar.close);updatePosUI();tryFillLimits(bar.close);draw()}catch(x){}};ws.onerror=()=>{setConn('bad');try{ws.close()}catch(x){}c()};ws.onclose=()=>{setConn('wait')}}catch(x){c()}})()}
function openPosition(side,price,size){position={side,entry:price,size,qty:size};st((side==='long'?'Long':'Short')+' @ '+fmt(price)+' × '+size);toast((side==='long'?'Long':'Short')+' × '+size);if(autoBr&&price>0){const slP=side==='long'?price*(1-slPct/100):price*(1+slPct/100);const tpP=side==='long'?price*(1+tpPct/100):price*(1-tpPct/100);orders=orders.filter(o=>o.type!=='sl'&&o.type!=='tp');orders.push({id:_oid++,type:'sl',price:+slP.toFixed(price>=1000?1:price>=1?2:5),qty:size});orders.push({id:_oid++,type:'tp',price:+tpP.toFixed(price>=1000?1:price>=1?2:5),qty:size});toast('SL/TP авто · '+slPct+'% / '+tpPct+'%')}updatePosUI();renderTrade();draw()}
function closePosition(){if(!position)return;const px=lastPx();if(px!=null){const pnl=position.side==='long'?(px-position.entry)*position.size:(position.entry-px)*position.size;st('закрыто PnL '+pnl.toFixed(2));toast('Закрыто · '+pnl.toFixed(2))}position=null;updatePosUI();renderTrade();draw()}
function updatePosUI(){const bar=$('posBar');if(!position){bar.classList.remove('on');return}bar.classList.add('on');const tag=$('posTag');tag.textContent=position.side==='long'?'LONG':'SHORT';tag.className='tag '+(position.side==='long'?'long':'short');$('posMeta').textContent=fmt(position.entry)+' × '+position.size;const px=lastPx();if(px!=null){const pnl=position.side==='long'?(px-position.entry)*position.size:(position.entry-px)*position.size;const el=$('posPnl');el.textContent=(pnl>=0?'+':'')+pnl.toFixed(2);el.className='pnl '+(pnl>=0?'up':'dn')}}
function tryFillLimits(px){const left=[];let closed=false;for(const o of orders){if(o.type==='sl'||o.type==='tp'){if(!position){left.push(o);continue}let hit=false;if(position.side==='long'){if(o.type==='sl'&&px<=o.price)hit=true;if(o.type==='tp'&&px>=o.price)hit=true}else{if(o.type==='sl'&&px>=o.price)hit=true;if(o.type==='tp'&&px<=o.price)hit=true}if(hit){const pnl=position.side==='long'?(px-position.entry)*position.size:(position.entry-px)*position.size;st((o.type==='sl'?'SL':'TP')+' · PnL '+pnl.toFixed(2));toast((o.type==='sl'?'Стоп':'Тейк')+' · '+pnl.toFixed(2));position=null;closed=true;updatePosUI()}else left.push(o);continue}if(o.type!=='limit'){left.push(o);continue}let fill=false;if(o.side==='buy'&&px<=o.price)fill=true;if(o.side==='sell'&&px>=o.price)fill=true;if(fill)openPosition(o.side==='buy'?'long':'short',o.price,o.qty||qty());else left.push(o)}if(closed){orders=left.filter(o=>o.type!=='sl'&&o.type!=='tp');renderTrade();draw();return}if(left.length!==orders.length){orders=left;renderTrade()}}
function breakEven(){if(!position){toast('Нет позиции');return}const px=position.entry;const exist=orders.find(o=>o.type==='sl');if(exist)exist.price=px;else orders.push({id:_oid++,type:'sl',price:px,qty:position.size});st('BE @ '+fmt(px));toast('Стоп в безубыток');draw();renderTrade()}
function riskHint(o,price){if(!position||(o.type!=='sl'&&o.type!=='tp'))return '';const pnl=position.side==='long'?(price-position.entry)*position.size:(position.entry-price)*position.size;const pct=((price-position.entry)/position.entry)*100*(position.side==='long'?1:-1);return ' · '+(pnl>=0?'+':'')+pnl.toFixed(2)+' ('+(pct>=0?'+':'')+pct.toFixed(2)+'%)'}
